server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_test
    username: root
    password: sahil1208
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
      show-sql: true
